SELECT * FROM COVIDDATABASE..COVIDDEATHS
ORDER BY 3,4

SELECT * FROM COVIDDATABASE..COVIDVACINATIONS
ORDER BY 3,4


SELECT LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION 
FROM COVIDDATABASE..COVIDDEATHS 
ORDER BY 1,2

--TOTAL CASES VS TOTAL DEATHS
--PROBABILITY OF DYING IF YOU CONTRACT COVID IN GHANA

SELECT LOCATION,DATE,TOTAL_CASES,TOTAL_DEATHS,(TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM COVIDDATABASE..COVIDDEATHS 
WHERE LOCATION = 'GHANA'
ORDER BY 1,2

--TOTAL CASES VS POPULATION
--SHOWS PERCENTAGE OF POPULATION THAT GOT COVID

SELECT LOCATION,DATE,TOTAL_CASES,POPULATION,(TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTION
FROM COVIDDATABASE..COVIDDEATHS 
--WHERE LOCATION = 'GHANA'
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

--LOOKING AT COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED
FROM COVIDDATABASE..COVIDDEATHS 
--WHERE LOCATION = 'GHANA'
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION,POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC


 

--SHOWING COUNTRIES WITH THE HIGHEST DEATHCOUNT PER POPULATION BREAKING IT DOWN BY CONTINENT

SELECT LOCATION,MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDATABASE..COVIDDEATHS
--WHERE LOCATION = 'GHANA'
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC

--SHOWING CONTINENTS WITH THE HIGHEST DEATH COUNT

SELECT CONTINENT,MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDATABASE..COVIDDEATHS
--WHERE LOCATION = 'GHANA'
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC


--HIGHEST INFECTION RATE AMONG AFRICA COUNTRIES

SELECT LOCATION,POPULATION,MAX(TOTAL_CASES) AS TOTALCASES,MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT,
MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTPOPULATIONINFECTED
FROM COVIDDATABASE..COVIDDEATHS
WHERE CONTINENT ='AFRICA'
GROUP BY LOCATION,POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC

--HIGHEST INFECTED AFRICA COUNTRY

SELECT LOCATION,POPULATION,SUM(NEW_CASES) AS TOTALCASES
FROM COVIDDATABASE..COVIDDEATHS
WHERE CONTINENT ='AFRICA'
GROUP BY LOCATION,POPULATION
ORDER BY TOTALCASES DESC



--HIGHEST DEATHRATE IN AFRICA
SELECT LOCATION,POPULATION,MAX(TOTAL_CASES) AS TOTALCASES,MAX(CAST(TOTAL_DEATHS AS INT)) AS TOTALDEATHCOUNT,
MAX(CAST(TOTAL_DEATHS AS INT))/POPULATION*100 AS DEATHPERCENT
FROM COVIDDATABASE..COVIDDEATHS
WHERE CONTINENT ='AFRICA'
GROUP BY LOCATION,POPULATION
ORDER BY TOTALDEATHCOUNT DESC

--LEAST INFECTED COUNTRY IN AFRICA
SELECT LOCATION,POPULATION,MAX(TOTAL_CASES) AS LEASTINFECTIONCOUNT
FROM COVIDDATABASE..COVIDDEATHS
WHERE CONTINENT ='AFRICA'
GROUP BY LOCATION,POPULATION
ORDER BY LEASTINFECTIONCOUNT ASC


--1
--GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS TOTALCASES,SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS,
SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM COVIDDATABASE..COVIDDEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2



--2
--TOTAL DEATH COUNT IN THE WORLD
SELECT CONTINENT,SUM(CAST(NEW_DEATHS AS INT)) AS TOTALDEATHCOUNT
FROM COVIDDATABASE..COVIDDEATHS
--WHERE LOCATION = 'GHANA'
WHERE CONTINENT IS NOT NULL
--AND LOCATION NOT IN ('WORLD','EUROPEAN UNION','INTERNATIONAL','UPPER MIDDLE INCOME','HIGH INCOME','LOWER MIDDLE INCOME','LOW INCOME')
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC


--3
--PERCETAGE OF POPULATION INFECTED 
SELECT LOCATION,POPULATION,SUM(NEW_CASES) AS HIGHESTINFECTIONCOUNT, SUM((NEW_CASES/POPULATION))*100 AS PERCENTPOPULATIONINFECTED
FROM COVIDDATABASE..COVIDDEATHS
--WHERE CONTINENT ='AFRICA'
GROUP BY LOCATION,POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC



--TOTAL CASES IN AFRICA
SELECT LOCATION,SUM(NEW_CASES) AS TOTALCASES
FROM COVIDDATABASE..COVIDDEATHS
WHERE CONTINENT ='AFRICA' AND NEW_CASES != 0
GROUP BY LOCATION 
ORDER BY TOTALCASES DESC


--TOTAL CASES PER DATE IN GHANA
SELECT DATE,SUM(NEW_CASES) AS TOTALCASES
FROM COVIDDATABASE..COVIDDEATHS
WHERE LOCATION ='GHANA' AND NEW_CASES != 0
GROUP BY DATE



--LOOKING AT TOTAL POPULATION VS VACCINATION

SELECT DEA.CONTINENT, DEA.LOCATION,DEA.DATE,DEA.POPULATION,MAX(VAC.TOTAL_VACCINATIONS) AS ROLLINGPEOPLEVACCINATED
FROM COVIDDATABASE..COVIDDEATHS DEA 
JOIN COVIDDATABASE..COVIDVACINATIONS VAC
ON DEA.LOCATION =VAC.LOCATION
AND DEA.DATE =VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
GROUP BY DEA.CONTINENT,DEA.LOCATION,DEA.DATE,DEA.POPULATION
ORDER BY 1,2,3


--CREATING VIEWS

CREATE VIEW PERCENTAGEPOPULATIONVACCINATED AS
SELECT DEA.CONTINENT, DEA.LOCATION,DEA.DATE,DEA.POPULATION,VAC.NEW_VACCINATIONS,
SUM(CONVERT(BIGINT, VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM COVIDDATABASE..COVIDVACINATIONS VAC
JOIN COVIDDATABASE..COVIDDEATHS DEA
ON DEA.LOCATION =VAC.LOCATION
AND DEA.DATE =VAC.DATE
WHERE DEA.CONTINENT ='AFRICA'
--ORDER BY 2,3


SELECT DEA.LOCATION,DEA.POPULATION,PPV.ROLLINGPEOPLEVACCINATED,(PPV.ROLLINGPEOPLEVACCINATED/DEA.POPULATION) AS PERCENTAGEVACCINATED
FROM COVIDDEATHS DEA
INNER JOIN PERCENTAGEPOPULATIONVACCINATED PPV
ON DEA.LOCATION = PPV.LOCATION
WHERE DEA.CONTINENT = 'AFRICA'


------PERCENTAGE FULLY VACCINATED/POPULATION-------
CREATE VIEW VACCINATEDTABLE1 AS 
SELECT DEA.LOCATION,DEA.POPULATION,SUM(DEA.NEW_CASES)AS TOTALCASES,SUM(CAST(VAC.TOTAL_VACCINATIONS AS INT))AS TOTALVACCINATED,
SUM(CAST(VAC.PEOPLE_FULLY_VACCINATED AS INT))AS FULLYVACCINATED,SUM(CAST( DEA.NEW_DEATHS AS INT)) AS TOTALDEATHS
FROM COVIDDATABASE..COVIDDEATHS DEA 
JOIN COVIDDATABASE..COVIDVACINATIONS VAC
ON DEA.LOCATION =VAC.LOCATION
AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT = 'AFRICA'
GROUP BY DEA.LOCATION,DEA.POPULATION
--ORDER  BY 1


SELECT DEA.LOCATION,DEA.POPULATION,SUM(DEA.NEW_CASES)AS TOTALCASES,FULLYVACCINATED,
(FULLYVACCINATED/DEA.POPULATION)* 100 AS PERCENTAGEPOPULATIONVACCINATED
FROM VACCINATEDTABLE VAC
INNER JOIN COVIDDEATHS DEA
ON VAC.LOCATION =DEA.LOCATION
GROUP BY DEA.LOCATION,DEA.POPULATION,VAC.FULLYVACCINATED
ORDER BY 1



